language: objective-c
osx_image: xcode7.3

# cache: cocoapods
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg" && sudo installer -pkg "Carthage.pkg" -target / && rm "Carthage.pkg"

env:
  - ACTION=test  PLATFORM=Mac     DESTINATION='platform=OS X'
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
  - ACTION=test  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'
  - ACTION=build PLATFORM=watchOS DESTINATION='platform=watchOS Simulator,name=Apple Watch - 38mm' 
script:
  - carthage bootstrap --platform $PLATFORM
  - set -o pipefail && xcodebuild -project DipUI/DipUI.xcodeproj -scheme DipUI -destination "$DESTINATION" $ACTION | xcpretty
  - pod lib lint --quick
  - carthage build --no-skip-current

notifications:
  email: false
